#!/usr/bin/env python3
"""Audit and safely sanitize co-simulation placement JSONL files.

The audit is intentionally strict: every retained non-empty line must contain a
finite RTT and a contiguous task-indexed placement plan. The generated manifest
contains a SHA-256 digest and row count for every dataset, plus corpus-level
missing/empty/corrupt inventories.

Sanitizing is only the first half of a repair. It removes malformed rows after
creating a byte-for-byte backup. The missing placement plans must then be
regenerated by ``generate_non_unique_placements_fast.py`` before the final
full-corpus audit. If the historical placement universe cannot be reproduced,
the canonical JSONL is archived out of the consumer path and the dataset is
explicitly recorded as excluded.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import os
import shutil
import sys
import tempfile
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


PROJECT_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SIM_ROOT = PROJECT_ROOT / "simulation_data"
DEFAULT_CORPORA = (
    "gnn_datasets_4tasks_1060_warmth_v2",
    "gnn_datasets_4tasks_sparse_warmth_v2",
    "gnn_datasets_4tasks_contention_v2",
    "gnn_datasets_4tasks_contention_v3",
)
DEFAULT_MANIFEST = DEFAULT_SIM_ROOT / "placement_integrity_manifest.json"


def _utc_now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def _plan_key(plan: Any) -> tuple[tuple[int, int], ...]:
    if not isinstance(plan, dict) or not plan:
        raise ValueError("placement_plan must be a non-empty object")
    try:
        task_ids = sorted(int(key) for key in plan)
    except (TypeError, ValueError) as exc:
        raise ValueError("placement_plan task IDs must be integers") from exc
    if task_ids != list(range(len(task_ids))):
        raise ValueError(f"placement_plan task IDs are not contiguous: {task_ids}")

    placements: list[tuple[int, int]] = []
    for task_id in task_ids:
        value = plan.get(str(task_id), plan.get(task_id))
        if (
            not isinstance(value, (list, tuple))
            or len(value) != 2
            or isinstance(value[0], bool)
            or isinstance(value[1], bool)
            or not isinstance(value[0], int)
            or not isinstance(value[1], int)
        ):
            raise ValueError(
                f"placement_plan[{task_id}] must be exactly two integers"
            )
        placements.append((value[0], value[1]))
    return tuple(placements)


def _parse_line(raw_line: bytes) -> tuple[dict[str, Any], tuple[tuple[int, int], ...]]:
    try:
        record = json.loads(raw_line)
    except (UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise ValueError(f"invalid JSON: {exc}") from exc
    if not isinstance(record, dict):
        raise ValueError("record must be an object")
    if set(record) != {"placement_plan", "rtt"}:
        raise ValueError(
            "record keys must be exactly placement_plan and rtt"
        )
    key = _plan_key(record["placement_plan"])
    rtt = record["rtt"]
    if isinstance(rtt, bool) or not isinstance(rtt, (int, float)):
        raise ValueError("rtt must be numeric")
    if not math.isfinite(float(rtt)) or float(rtt) < 0:
        raise ValueError("rtt must be finite and non-negative")
    return record, key


def scan_jsonl(path: Path, *, collect_valid_lines: bool = False) -> dict[str, Any]:
    digest = hashlib.sha256()
    seen: dict[tuple[tuple[int, int], ...], tuple[float, int]] = {}
    valid_lines: list[bytes] | None = [] if collect_valid_lines else None
    invalid: list[dict[str, Any]] = []
    duplicate_lines: list[int] = []
    conflicting_duplicates: list[dict[str, Any]] = []
    duplicate_count = 0
    valid_rows = 0
    nonempty_rows = 0
    min_rtt: float | None = None

    with path.open("rb") as stream:
        for line_number, raw_line in enumerate(stream, 1):
            digest.update(raw_line)
            stripped = raw_line.strip()
            if not stripped:
                continue
            nonempty_rows += 1
            try:
                record, key = _parse_line(stripped)
            except ValueError as exc:
                invalid.append(
                    {
                        "line": line_number,
                        "reason": str(exc),
                        "preview_hex": stripped[:80].hex(),
                    }
                )
                continue
            rtt = float(record["rtt"])
            if key in seen:
                duplicate_count += 1
                if len(duplicate_lines) < 100:
                    duplicate_lines.append(line_number)
                first_rtt, first_line = seen[key]
                if not math.isclose(first_rtt, rtt, abs_tol=1e-9):
                    if len(conflicting_duplicates) < 100:
                        conflicting_duplicates.append(
                            {
                                "line": line_number,
                                "first_line": first_line,
                                "rtt": rtt,
                                "first_rtt": first_rtt,
                            }
                        )
            else:
                seen[key] = (rtt, line_number)
            valid_rows += 1
            min_rtt = (
                rtt
                if min_rtt is None
                else min(min_rtt, rtt)
            )
            if valid_lines is not None:
                valid_lines.append(stripped + b"\n")

    return {
        "path": str(path),
        "size_bytes": path.stat().st_size,
        "sha256": digest.hexdigest(),
        "nonempty_rows": nonempty_rows,
        "valid_rows": valid_rows,
        "unique_plans": len(seen),
        "invalid_rows": invalid,
        "duplicate_plan_count": duplicate_count,
        "duplicate_plan_lines": duplicate_lines,
        "conflicting_duplicate_rtt": conflicting_duplicates,
        "min_rtt": min_rtt,
        "valid_lines": valid_lines,
    }


def sanitize_jsonl(path: Path, manifest: dict[str, Any]) -> None:
    scan = scan_jsonl(path, collect_valid_lines=True)
    invalid = scan["invalid_rows"]
    if not invalid:
        raise RuntimeError(f"Refusing to sanitize clean file: {path}")
    if scan["valid_rows"] == 0:
        raise RuntimeError(f"Refusing to sanitize file with no valid rows: {path}")

    timestamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    backup = path.with_name(f"{path.name}.corrupt-{timestamp}.bak")
    if backup.exists():
        raise FileExistsError(f"Backup already exists: {backup}")
    shutil.copy2(path, backup)

    valid_lines: list[bytes] = scan["valid_lines"]
    fd, temp_name = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    temp_path = Path(temp_name)
    try:
        with os.fdopen(fd, "wb") as stream:
            stream.writelines(valid_lines)
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temp_path, path)
    finally:
        if temp_path.exists():
            temp_path.unlink()

    repaired = scan_jsonl(path)
    if repaired["invalid_rows"] or repaired["valid_rows"] != scan["valid_rows"]:
        raise RuntimeError(f"Post-sanitize validation failed: {path}")

    manifest.setdefault("repairs", []).append(
        {
            "timestamp": _utc_now(),
            "action": "sanitized_invalid_rows_pending_regeneration",
            "path": str(path),
            "backup": str(backup),
            "original_sha256": scan["sha256"],
            "sanitized_sha256": repaired["sha256"],
            "removed_rows": invalid,
            "retained_rows": repaired["valid_rows"],
        }
    )
    print(
        f"SANITIZED {path}: removed={len(invalid)} "
        f"retained={repaired['valid_rows']} backup={backup.name}"
    )


def exclude_jsonl(
    path: Path,
    manifest: dict[str, Any],
    *,
    reason: str,
) -> None:
    if not path.exists():
        raise FileNotFoundError(f"Cannot exclude missing canonical JSONL: {path}")
    dataset_dir = path.parent.parent
    dataset_key = str(dataset_dir)
    active_exclusions = {
        row.get("dataset_dir")
        for row in manifest.setdefault("exclusions", [])
        if row.get("active", True)
    }
    if dataset_key in active_exclusions:
        raise RuntimeError(f"Dataset is already excluded: {dataset_dir}")

    scan = scan_jsonl(path)
    metadata_path = dataset_dir / "placement_metadata.json"
    metadata: dict[str, Any] = {}
    if metadata_path.exists():
        try:
            loaded = json.loads(metadata_path.read_text())
            if isinstance(loaded, dict):
                metadata = loaded
        except (OSError, json.JSONDecodeError):
            metadata = {}

    timestamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    archived = path.with_name(f"{path.name}.incomplete-excluded-{timestamp}")
    if archived.exists():
        raise FileExistsError(f"Exclusion archive already exists: {archived}")
    os.replace(path, archived)

    original_backups = sorted(
        str(candidate)
        for candidate in path.parent.glob(f"{path.name}.corrupt-*.bak")
    )
    manifest["exclusions"].append(
        {
            "timestamp": _utc_now(),
            "active": True,
            "dataset_dir": dataset_key,
            "canonical_path": str(path),
            "archived_sanitized_path": str(archived),
            "original_corrupt_backups": original_backups,
            "reason": reason,
            "retained_valid_rows": scan["valid_rows"],
            "metadata_num_placements": metadata.get("num_placements"),
            "metadata_completed": metadata.get("completed"),
            "sanitized_sha256": scan["sha256"],
        }
    )
    print(
        f"EXCLUDED {dataset_dir}: retained={scan['valid_rows']} "
        f"metadata_completed={metadata.get('completed')} archive={archived.name}"
    )


def exclude_missing_dataset(
    dataset_dir: Path,
    manifest: dict[str, Any],
    *,
    reason: str,
) -> None:
    if not dataset_dir.is_dir():
        raise FileNotFoundError(f"Cannot exclude missing dataset directory: {dataset_dir}")
    canonical = dataset_dir / "placements" / "placements.jsonl"
    if canonical.exists():
        raise RuntimeError(
            f"Use --exclude with the canonical JSONL when it exists: {canonical}"
        )
    dataset_key = str(dataset_dir)
    if any(
        row.get("dataset_dir") == dataset_key and row.get("active", True)
        for row in manifest.setdefault("exclusions", [])
    ):
        raise RuntimeError(f"Dataset is already excluded: {dataset_dir}")
    present_files = sorted(
        str(path.relative_to(dataset_dir))
        for path in dataset_dir.rglob("*")
        if path.is_file()
    )
    manifest["exclusions"].append(
        {
            "timestamp": _utc_now(),
            "active": True,
            "dataset_dir": dataset_key,
            "canonical_path": str(canonical),
            "archived_sanitized_path": None,
            "original_corrupt_backups": [],
            "reason": reason,
            "present_files": present_files,
        }
    )
    print(f"EXCLUDED MISSING SWEEP {dataset_dir}: files={present_files}")


def deduplicate_jsonl(path: Path, manifest: dict[str, Any]) -> None:
    scan = scan_jsonl(path)
    if scan["invalid_rows"]:
        raise RuntimeError(f"Refusing to deduplicate corrupt JSONL: {path}")
    if scan["duplicate_plan_count"] == 0:
        raise RuntimeError(f"Refusing to deduplicate file without duplicates: {path}")
    if scan["conflicting_duplicate_rtt"]:
        raise RuntimeError(
            f"Conflicting RTTs for duplicate plans in {path}: "
            f"{scan['conflicting_duplicate_rtt'][:3]}"
        )

    retained_lines: list[bytes] = []
    seen: set[tuple[tuple[int, int], ...]] = set()
    with path.open("rb") as stream:
        for raw_line in stream:
            stripped = raw_line.strip()
            if not stripped:
                continue
            _, key = _parse_line(stripped)
            if key in seen:
                continue
            seen.add(key)
            retained_lines.append(stripped + b"\n")

    timestamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    backup = path.with_name(f"{path.name}.duplicates-{timestamp}.bak")
    shutil.copy2(path, backup)
    fd, temp_name = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    temp_path = Path(temp_name)
    try:
        with os.fdopen(fd, "wb") as stream:
            stream.writelines(retained_lines)
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temp_path, path)
    finally:
        if temp_path.exists():
            temp_path.unlink()

    repaired = scan_jsonl(path)
    if (
        repaired["invalid_rows"]
        or repaired["duplicate_plan_count"]
        or repaired["valid_rows"] != scan["unique_plans"]
    ):
        raise RuntimeError(f"Post-deduplication validation failed: {path}")
    manifest.setdefault("repairs", []).append(
        {
            "timestamp": _utc_now(),
            "action": "removed_exact_duplicate_placement_plans",
            "path": str(path),
            "backup": str(backup),
            "original_sha256": scan["sha256"],
            "deduplicated_sha256": repaired["sha256"],
            "removed_rows": scan["duplicate_plan_count"],
            "retained_rows": repaired["valid_rows"],
        }
    )
    print(
        f"DEDUPLICATED {path}: removed={scan['duplicate_plan_count']} "
        f"retained={repaired['valid_rows']} backup={backup.name}"
    )


def _load_manifest(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {"schema_version": 1, "repairs": [], "exclusions": []}
    try:
        loaded = json.loads(path.read_text())
    except (OSError, json.JSONDecodeError) as exc:
        raise RuntimeError(f"Cannot load existing manifest {path}: {exc}") from exc
    if not isinstance(loaded, dict):
        raise RuntimeError(f"Existing manifest must be a JSON object: {path}")
    loaded.setdefault("schema_version", 1)
    loaded.setdefault("repairs", [])
    loaded.setdefault("exclusions", [])
    return loaded


def _best_json_rtt(dataset_dir: Path) -> float | None:
    path = dataset_dir / "best.json"
    if not path.exists():
        return None
    try:
        value = json.loads(path.read_text()).get("rtt")
        return float(value) if value is not None else None
    except (OSError, ValueError, TypeError, json.JSONDecodeError):
        return None


def audit_corpora(
    sim_root: Path,
    corpus_names: list[str],
    manifest: dict[str, Any],
) -> bool:
    corpus_reports: dict[str, Any] = {}
    total_datasets = 0
    total_jsonl = 0
    total_rows = 0
    total_excluded = 0
    all_clean = True
    active_exclusions = {
        row.get("dataset_dir"): row
        for row in manifest.get("exclusions", [])
        if row.get("active", True)
    }

    for corpus_name in corpus_names:
        corpus_dir = sim_root / corpus_name
        if not corpus_dir.is_dir():
            raise FileNotFoundError(f"Missing corpus directory: {corpus_dir}")
        dataset_dirs = sorted(
            path for path in corpus_dir.glob("ds_*") if path.is_dir()
        )
        missing: list[str] = []
        empty: list[str] = []
        corrupt: list[str] = []
        duplicates: list[str] = []
        best_rtt_mismatch: list[str] = []
        excluded: list[str] = []
        excluded_with_canonical_jsonl: list[str] = []
        datasets: dict[str, Any] = {}

        for dataset_dir in dataset_dirs:
            jsonl_path = dataset_dir / "placements" / "placements.jsonl"
            if str(dataset_dir) in active_exclusions:
                excluded.append(dataset_dir.name)
                if jsonl_path.exists():
                    excluded_with_canonical_jsonl.append(dataset_dir.name)
                continue
            if not jsonl_path.exists():
                missing.append(dataset_dir.name)
                continue
            scan = scan_jsonl(jsonl_path)
            scan.pop("valid_lines", None)
            best_rtt = _best_json_rtt(dataset_dir)
            scan["best_json_rtt"] = best_rtt
            if (
                best_rtt is not None
                and scan["min_rtt"] is not None
                and not math.isclose(best_rtt, scan["min_rtt"], abs_tol=1e-6)
            ):
                best_rtt_mismatch.append(dataset_dir.name)
            if scan["nonempty_rows"] == 0:
                empty.append(dataset_dir.name)
            if scan["invalid_rows"]:
                corrupt.append(dataset_dir.name)
            if scan["duplicate_plan_count"]:
                duplicates.append(dataset_dir.name)
            datasets[dataset_dir.name] = scan
            total_jsonl += 1
            total_rows += scan["valid_rows"]

        clean = not (
            missing
            or empty
            or corrupt
            or duplicates
            or excluded_with_canonical_jsonl
        )
        all_clean = all_clean and clean
        total_datasets += len(dataset_dirs)
        total_excluded += len(excluded)
        corpus_reports[corpus_name] = {
            "clean": clean,
            "dataset_directories": len(dataset_dirs),
            "retained_datasets": len(dataset_dirs) - len(excluded),
            "excluded_datasets": excluded,
            "jsonl_files": len(datasets),
            "valid_rows": sum(row["valid_rows"] for row in datasets.values()),
            "missing_jsonl": missing,
            "empty_jsonl": empty,
            "corrupt_jsonl": corrupt,
            "duplicate_plan_jsonl": duplicates,
            "excluded_with_canonical_jsonl": excluded_with_canonical_jsonl,
            "best_json_rtt_mismatch": best_rtt_mismatch,
            "datasets": datasets,
        }
        print(
            f"{corpus_name}: clean={clean} datasets={len(dataset_dirs)} "
            f"retained={len(dataset_dirs) - len(excluded)} excluded={len(excluded)} "
            f"jsonl={len(datasets)} rows={corpus_reports[corpus_name]['valid_rows']} "
            f"missing={len(missing)} empty={len(empty)} corrupt={len(corrupt)} "
            f"duplicates={len(duplicates)} best_mismatch={len(best_rtt_mismatch)}"
        )

    manifest.update(
        {
            "schema_version": 1,
            "generated_at": _utc_now(),
            "sim_root": str(sim_root),
            "clean": all_clean,
            "summary": {
                "corpora": len(corpus_names),
                "dataset_directories": total_datasets,
                "retained_datasets": total_datasets - total_excluded,
                "excluded_datasets": total_excluded,
                "jsonl_files": total_jsonl,
                "valid_rows": total_rows,
            },
            "corpora": corpus_reports,
        }
    )
    return all_clean


def _write_manifest(path: Path, manifest: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, temp_name = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    temp_path = Path(temp_name)
    try:
        with os.fdopen(fd, "w") as stream:
            json.dump(manifest, stream, indent=2, sort_keys=True)
            stream.write("\n")
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temp_path, path)
    finally:
        if temp_path.exists():
            temp_path.unlink()


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--sim-root", type=Path, default=DEFAULT_SIM_ROOT)
    parser.add_argument(
        "--corpus",
        action="append",
        dest="corpora",
        help="Corpus directory name under --sim-root; repeatable",
    )
    parser.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST)
    parser.add_argument(
        "--sanitize",
        action="append",
        type=Path,
        default=[],
        help="Malformed placements.jsonl to back up and sanitize; repeatable",
    )
    parser.add_argument(
        "--sanitize-only",
        action="store_true",
        help="Apply requested sanitizations/exclusions without the full audit",
    )
    parser.add_argument(
        "--exclude",
        action="append",
        type=Path,
        default=[],
        help="Incomplete canonical placements.jsonl to archive and exclude; repeatable",
    )
    parser.add_argument(
        "--exclusion-reason",
        default=(
            "Historical full placement sweep is corrupt or truncated and cannot "
            "be reproduced exactly from local artifacts"
        ),
        help="Reason recorded for every --exclude in this invocation",
    )
    parser.add_argument(
        "--exclude-dataset",
        action="append",
        type=Path,
        default=[],
        help="Dataset directory whose canonical placement JSONL was never generated",
    )
    parser.add_argument(
        "--deduplicate",
        action="append",
        type=Path,
        default=[],
        help="JSONL whose exact duplicate plans should be removed; repeatable",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    manifest = _load_manifest(args.manifest)
    for path in args.sanitize:
        resolved = path if path.is_absolute() else PROJECT_ROOT / path
        sanitize_jsonl(resolved, manifest)
    for path in args.exclude:
        resolved = path if path.is_absolute() else PROJECT_ROOT / path
        exclude_jsonl(resolved, manifest, reason=args.exclusion_reason)
    for path in args.exclude_dataset:
        resolved = path if path.is_absolute() else PROJECT_ROOT / path
        exclude_missing_dataset(
            resolved,
            manifest,
            reason=args.exclusion_reason,
        )
    for path in args.deduplicate:
        resolved = path if path.is_absolute() else PROJECT_ROOT / path
        deduplicate_jsonl(resolved, manifest)

    if args.sanitize_only:
        manifest["generated_at"] = _utc_now()
        manifest["clean"] = False
        manifest["status"] = "mutations_applied_pending_full_audit"
        _write_manifest(args.manifest, manifest)
        return 0

    corpus_names = args.corpora or list(DEFAULT_CORPORA)
    clean = audit_corpora(args.sim_root, corpus_names, manifest)
    manifest["status"] = "clean" if clean else "integrity_failures_detected"
    _write_manifest(args.manifest, manifest)
    print(f"Manifest: {args.manifest}")
    return 0 if clean else 1


if __name__ == "__main__":
    sys.exit(main())
